sudo: required
dist: trusty
branches:
    only: master
addons:
    apt:
        packages:
            - doxygen
env:
    global:
        - MAKEFLAGS="-j"
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full valgrind
script:
- make NO_VALGRIND=true
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/html/
    on:
        branch: master
