sudo: required
dist: trusty
branches:
    only:
        - master
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
script:
- make -C thesis
- make test_all -C source
