dist: trusty
branches:
    only: master
language: r
addons:
    apt:
        packages:
            - doxygen
            - python-pygments
env:
    global:
        - MAKEFLAGS="-j"
before_install:
    - tlmgr install texliveonfly
    - tlmgr install latexmk
    - tlmgr install babel-portuges
    - tlmgr install courier
    - tlmgr install lm
    - tlmgr install luaotfload
script:
    - cd thesis && texliveonfly main.tex && cd ..
    - make full NO_VALGRIND=true
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/html/
    on:
        branch: master
